# Generated by Django 3.0.3 on 2020-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('request', 'request'), ('waiting', 'waiting'), ('to_airport', 'to_airport'), ('to_hotel', 'to_hotel'), ('dropped_off', 'dropped_off')], default='request', max_length=20)),
            ],
        ),
    ]
