# Generated by Django 3.0.3 on 2020-02-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('stop', 'stop'), ('caution', 'caution'), ('gogogo', 'gogogo')], default='stop', max_length=20)),
            ],
        ),
    ]
